### PR TITLE
Add Actions CI workflow

### PR DESCRIPTION
**Pull request by andreas**
Before making more contributions, I figured it would be good to have some CI set up. Here's an attempt at an Actions CI workflow. It only includes Ubuntu latest and fixed versions of Node, emcc and binaryen, but could be expanded to a matrix strategy later.

Example output: https://github.com/andreas/roaring-wasm/actions/runs/5002284107

### CODE REVIEW

**Comment by SalvatorePreviti** [comment]
Ok, before doing this, I think this projects needs a bit of cleanup and refactoring, let me try to update things

**Comment by andreas** [comment]
I was thinking having CI set up would actually enable doing cleanup and refactoring without inadvertently breaking anything 🙂

In the spirit of trying to prevent duplicate/overlapping work, this is one of the primary changes I'd like to land: https://github.com/SalvatorePreviti/roaring-wasm/commit/7f4f70e64f4088bc3fd9d69abc188c56334b0dfe (I intended to submit as a PR later). Maybe it's orthogonal to what you have in mind!

**Comment by SalvatorePreviti** [comment]
Oh seems to be fine :) I am working on this branch, https://github.com/SalvatorePreviti/roaring-wasm/tree/big-project-refactor - I am not changing the code or the implementation in this PR, just the project structure, updating packages, the build code, moving from jest to mocha (lighter and messes up less with node), make the library loadable in browser via webpack. You should not have much conflicts in the work you are doing in the other PR. I am adding the CI workflow based on the one you wrote here in that pull request

**Comment by SalvatorePreviti** [comment]
@andreas based on this I merged the pull request https://github.com/SalvatorePreviti/roaring-wasm/pull/14 that adds testing in CI as well, so closing this one

**Pull request closed without merging**
